name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js for frontend
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Set up Node.js for backend
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Start backend server
        run: |
          cd backend
          npm run dev &
        env:
          NODE_ENV: test 

      - name: Wait for backend server
        run: npx wait-on http://localhost:5000 

      - name: Start frontend server
        run: |
          cd frontend
          npm run dev &
        env:
          CI: true 

      - name: Wait for frontend server
        run: npx wait-on http://localhost:5173 

      - name: Run Jest tests
        run: |
          cd backend
          npm test

      - name: Run Cypress tests
        run: |
          cd frontend
          npx cypress run
